# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  ImageName: 'naginagesh/azure-pipeline-image-test:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        imageName: '$(ImageName)' 
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          nagesh-docker-registry
        repository: '$(ImageName)'
        command: push